export const SET_LANG = "SET_LANG";
export const SET_TOKEN = "SET_TOKEN";
export const ACTIVATE_TAB = "ACTIVATE_TAB";
export const AUTH_DIALOG_OPEN = "AUTH_DIALOG_OPEN";
export const REMOVE_AUTH_MESSAGE = "REMOVE_AUTH_MESSAGE";

// GET
export const GET_MAIN = "GET_MAIN";
export const GET_MAIN_FAILED = "GET_MAIN_FAILED";
export const GET_MAIN_SUCCESS = "GET_MAIN_SUCCESS";

export const GET_WEATHER = "GET_WEATHER";
export const GET_WEATHER_FAILED = "GET_WEATHER_FAILED";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";

export const GET_LOCAL_NEWS = "GET_LOCAL_NEWS";
export const GET_LOCAL_NEWS_FAILED = "GET_LOCAL_NEWS_FAILED";
export const GET_LOCAL_NEWS_SUCCESS = "GET_LOCAL_NEWS_SUCCESS";

export const GET_GLOBAL_NEWS = "GET_GLOBAL_NEWS";
export const GET_GLOBAL_NEWS_FAILED = "GET_GLOBAL_NEWS_FAILED";
export const GET_GLOBAL_NEWS_SUCCESS = "GET_GLOBAL_NEWS_SUCCESS";

export const GET_CHAMPIONSHIPS = "GET_CHAMPIONSHIPS";
export const GET_CHAMPIONSHIPS_FAILED = "GET_CHAMPIONSHIPS_FAILED";
export const GET_CHAMPIONSHIPS_SUCCESS = "GET_CHAMPIONSHIPS_SUCCESS";

export const GET_VIDEO_NEWS = "GET_VIDEO_NEWS";
export const GET_VIDEO_NEWS_FAILED = "GET_VIDEO_NEWS_FAILED";
export const GET_VIDEO_NEWS_SUCCESS = "GET_VIDEO_NEWS_SUCCESS";

export const GET_FEDERATION_SPORTS = "GET_FEDERATION_SPORTS";
export const GET_FEDERATION_SPORTS_FAILED = "GET_FEDERATION_SPORTS_FAILED";
export const GET_FEDERATION_SPORTS_SUCCESS = "GET_FEDERATION_SPORTS_SUCCESS";

export const GET_FEDERATION_TRAINERS = "GET_FEDERATION_TRAINERS";
export const GET_FEDERATION_TRAINERS_FAILED = "GET_FEDERATION_TRAINERS_FAILED";
export const GET_FEDERATION_TRAINERS_SUCCESS =
  "GET_FEDERATION_TRAINERS_SUCCESS";

export const GET_FEDERATION_ATHLETES = "GET_FEDERATION_ATHLETES";
export const GET_FEDERATION_ATHLETES_FAILED = "GET_FEDERATION_ATHLETES_FAILED";
export const GET_FEDERATION_ATHLETES_SUCCESS =
  "GET_FEDERATION_ATHLETES_SUCCESS";

export const GET_GYMS_AND_CLUBS_FILTER = "GET_GYMS_AND_CLUBS_FILTER";
export const GET_GYMS_AND_CLUBS_FILTER_FAILED =
  "GET_GYMS_AND_CLUBS_FILTER_FAILED";
export const GET_GYMS_AND_CLUBS_FILTER_SUCCESS =
  "GET_GYMS_AND_CLUBS_FILTER_SUCCESS";

export const GET_HEALTH_CARE_DEPARTMENTS = "GET_HEALTH_CARE_DEPARTMENTS";
export const GET_HEALTH_CARE_DEPARTMENTS_FAILED =
  "GET_HEALTH_CARE_DEPARTMENTS_FAILED";
export const GET_HEALTH_CARE_DEPARTMENTS_SUCCESS =
  "GET_HEALTH_CARE_DEPARTMENTS_SUCCESS";

export const GET_COMPETITIONS = "GET_COMPETITIONS";
export const GET_COMPETITIONS_FAILED = "GET_COMPETITIONS_FAILED";
export const GET_COMPETITIONS_SUCCESS = "GET_COMPETITIONS_SUCCESS";

export const GET_COMPETITION_FILTERS = "GET_COMPETITION_FILTERS";
export const GET_COMPETITION_FILTERS_FAILED = "GET_COMPETITION_FILTERS_FAILED";
export const GET_COMPETITION_FILTERS_SUCCESS =
  "GET_COMPETITION_FILTERS_SUCCESS";

// PATCH
export const PATCH_SPORT_NEWS_VIEWS = "PATCH_SPORT_NEWS_VIEWS";
export const PATCH_SPORT_NEWS_VIEWS_SUCCESS = "PATCH_SPORT_NEWS_VIEWS_SUCCESS";
export const PATCH_SPORT_NEWS_VIEWS_FAILED = "PATCH_SPORT_NEWS_VIEWS_FAILED";

export const PATCH_TRAINER_VIEWS = "PATCH_TRAINER_VIEWS";
export const PATCH_TRAINER_VIEWS_SUCCESS = "PATCH_TRAINER_VIEWS_SUCCESS";
export const PATCH_TRAINER_VIEWS_FAILED = "PATCH_TRAINER_VIEWS_FAILED";

export const PATCH_ATHLETE_VIEWS = "PATCH_ATHLETE_VIEWS";
export const PATCH_ATHLETE_VIEWS_SUCCESS = "PATCH_ATHLETE_VIEWS_SUCCESS";
export const PATCH_ATHLETE_VIEWS_FAILED = "PATCH_ATHLETE_VIEWS_FAILED";

// POST
export const POST_LOGIN = "POST_LOGIN";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";

export const POST_SEARCH = "POST_SEARCH";
export const POST_SEARCH_FAILED = "POST_SEARCH_FAILED";
export const POST_SEARCH_SUCCESS = "POST_SEARCH_SUCCESS";

export const POST_GYMS_AND_CLUBS_FILTER = "POST_GYMS_AND_CLUBS_FILTER";
export const POST_GYMS_AND_CLUBS_FILTER_FAILED =
  "POST_GYMS_AND_CLUBS_FILTER_FAILED";
export const POST_GYMS_AND_CLUBS_FILTER_SUCCESS =
  "POST_GYMS_AND_CLUBS_FILTER_SUCCESS";

export const POST_COMPETITION_FILTER = "POST_COMPETITION_FILTER";
export const POST_COMPETITION_FILTER_FAILED = "POST_COMPETITION_FILTER_FAILED";
export const POST_COMPETITION_FILTER_SUCCESS =
  "POST_COMPETITION_FILTER_SUCCESS";
