export const OPEN_SIDENAV = "OPEN_SIDENAV";
export const SIDENAV_TYPE = "SIDENAV_TYPE";
export const SIDENAV_COLOR = "SIDENAV_COLOR";
export const TRANSPARENT_NAVBAR = "TRANSPARENT_NAVBAR";
export const FIXED_NAVBAR = "FIXED_NAVBAR";
export const OPEN_CONFIGURATOR = "OPEN_CONFIGURATOR";
